script: bash ./deploy.sh
language: php
php:
- 7.2
env:
  global:
  - GH_REF: github.com/UDOOboard/Bolt-Docs.git
  - secure: fLhxRWGPpqVG8zvPtZmmqoKOsx7V9BFJTXNdVgTN6QrwQzRcBeqMRikacBFHOy7CkGLAL+dUumg45x6kX8rkrneEVLQc/g0ZVdVoiPWDO72E8eez1f6hWrWd5ElSqYgWFzW5uA7Ox++d+S1dW9jHHXSC8uBOHVzLtHyIfrr31sCwPXX/1ILiSW7DtBNJ4Wa07cSojmrukc7Km/tOG3QGA80vIYVP27/U7QGq0f5JBRtGinJt7xDuyXj8v7tEj5+GSkdVZAptO4d4C9Hv6rjQC6dYP3l6vnpweypV1Aq7k4T0M2P76w+E9crSuGjB0c3PDAM2DYonViie6SULTRLKIHPslbE8UGkyuyqit5D30/PKhRR/nikMShCPQN2mLTgM1+0rWXgCXl+outwhFph64KzKy7V2Wc1MsRwgI258qzDWB7fI/3gtuVKSImCBlBEJpxjz4rCYO53K4T9OeKhz8fMx1nnp0bMmpfBj0sskTWxBMtv4DBpXebaiWeM9WQa+CaQJbaxCh/eiihBSuyroaHoLo+MU5SyT7WexY7Gwg/mZEtq0u0kxYh0zDUBwyRUGPON4xB86C9XmMr6m22fmZvbN0zNSmGN0BF9bNVI2eZrwPl3756v1P8tigv9S6tAo7d3A9qOulnMpAJK6rnL4h0gMFGvzkxuy8ohnwSeKWDo=
